### ISSUE TITLE
The deeplab backbone goes wrong

### ISSUE THREAD

**Issue by synsin0** [ybarancan/BEV_feat_stitch#5]
Environment:
tensorflow-gpu==1.15.0  tensorflow/models from latest branch of https://github.com/tensorflow/models

Error info:
python nuscenes_train.py 
WARNING:tensorflow:From ./models/research/deeplab/core/conv2d_ws.py:40: The name tf.layers.Layer is deprecated. Please use tf.compat.v1.layers.Layer instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 50.315 seconds.
======
Reverse indexing ...
Done reverse indexing in 3.6 seconds.
======
2022-02-28 22:22:35,768 EXPERIMENT : nuscenes_exp
2022-02-28 22:22:35,769 THIS IS ./scratch_net/mapmaker_github/logdir/deeplabFalse
2022-02-28 22:22:35,774 EXPERIMENT : nuscenes_exp
2022-02-28 22:22:35,774 THIS IS : ./scratch_net/mapmaker_github/logdir/deeplabFalse
2022-02-28 22:22:35,776 EXPERIMENT NAME: nuscenes_exp
2022-02-28 22:22:35.794378: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2022-02-28 22:22:35.844335: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3609600000 Hz
2022-02-28 22:22:35.846466: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5633061c2500 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-02-28 22:22:35.846529: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-02-28 22:22:35.877826: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-02-28 22:22:36.004477: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-28 22:22:36.004714: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56330620a5c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2022-02-28 22:22:36.004737: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3080, Compute Capability 8.6
2022-02-28 22:22:36.007727: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-28 22:22:36.009227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 3080 major: 8 minor: 6 memoryClockRate(GHz): 1.71
pciBusID: 0000:01:00.0
2022-02-28 22:22:36.013977: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2022-02-28 22:22:36.031509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2022-02-28 22:22:36.039224: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2022-02-28 22:22:36.042349: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2022-02-28 22:22:36.058427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2022-02-28 22:22:36.070031: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2022-02-28 22:22:36.100582: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2022-02-28 22:22:36.100733: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-28 22:22:36.100839: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-28 22:22:36.101360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-02-28 22:22:36.101623: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2022-02-28 22:22:36.102700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-02-28 22:22:36.102709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2022-02-28 22:22:36.102950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2022-02-28 22:22:36.103016: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-28 22:22:36.103076: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-28 22:22:36.103138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8539 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:01:00.0, compute capability: 8.6)
WARNING:tensorflow:From /home/yining/BEV_feat_stitch/mem_net.py:967: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

2022-02-28 22:22:36,121 From /home/yining/BEV_feat_stitch/mem_net.py:967: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

2022-02-28 22:22:36,122 IMAGE SHAPE [448, 800]
WARNING:tensorflow:From ./models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2022-02-28 22:22:36,122 From ./models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
2022-02-28 22:22:36,124 From /home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tf_slim/layers/layers.py:1089: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From ./models/research/deeplab/core/utils.py:41: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

2022-02-28 22:22:36,667 From ./models/research/deeplab/core/utils.py:41: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

Traceback (most recent call last):
  File "nuscenes_train.py", line 1422, in <module>
    main()
  File "nuscenes_train.py", line 1415, in main
    run_training(continue_run)
  File "nuscenes_train.py", line 329, in run_training
    image_total_backbone_out, image_total_relative_endpoints, image_total_end_points  =mem_net.image_encoder(images_placeholder,no_mask_tensor,my_model_options,downsample_stages=4,use_deeplab=use_deeplab,is_training=training_time_placeholder, reuse=False)
  File "/home/yining/BEV_feat_stitch/mem_net.py", line 971, in image_encoder
    backbone_out, relative_end_points, endpoints = backbone_deeplab(input_img,input_mask,scope,my_model_options,is_training=is_training, reuse=reuse)
  File "/home/yining/BEV_feat_stitch/mem_net.py", line 1027, in backbone_deeplab
    relative_endpoints.append(modified_endpoints['xception_65/entry_flow/block2/unit_1/xception_module/separable_conv2_pointwise'])
KeyError: 'xception_65/entry_flow/block2/unit_1/xception_module/separable_conv2_pointwise'

I record modified_endpoints but not find the following keys. Where goes something wrong?

**Comment by ybarancan** [comment]
Can you provide the list of keys obtained in line 1019: for entry in list(end_points.keys()): ? I think the backbone used for deeplab is not xception in your case. You might need to change the backbone type in the tensorflow-models library. To do this:

Change line 50 in tensorflow/models/blob/master/research/deeplab/common.py from mobile_net to =>
flags.DEFINE_string('model_variant', 'xception_65', 'DeepLab model variant.') .

Let me know if it solves the problem.

**Comment by synsin0** [comment]
After changing line 50 in deeplab/common.py the error is solved. 
After the training process starts, another error during training process is like:
2022-03-01 11:50:28,726 EPOCH : 0
2022-03-01 11:50:28,829 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:28,933 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,037 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,140 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,244 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,348 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,451 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,554 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,658 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,761 Exception empty range for randrange() (0,-2, -2)
2022-03-01 11:50:29,865 Exception empty range for randrange() (0,-2, -2)
......

It appears very quickly and stays constant, so I guess it may be a image cropping problem. Look forward to your reply.

**Comment by ybarancan** [comment]
That looks like it is coming from line 1208 in train file. 
frame_ids.append(random.randint(frame_ids[-1]+1, np.min([seq_length-(n_frames_per_seq-frame_number),frame_ids[-1]+max_interval_between_frames])))

Can you check if the sequence is correctly loaded by printing 

all_images_list = sorted(glob.glob(os.path.join(current_dir,'img*.png')))
all_labels_list = sorted(glob.glob(os.path.join(current_dir,'label*.png')))

**Comment by ShangWeize** [comment]
0 successful operations.
0 derived errors ignored.
Original stack trace for 'save/RestoreV2':
  File "nuscenes_test.py", line 837, in <module>
    main()
  File "nuscenes_test.py", line 831, in main
    run_training(continue_run)
  File "nuscenes_test.py", line 392, in run_training
    saver = tf.train.Saver(max_to_keep=2)

**Load the provided trained model, there is this problem**

**Comment by ShangWeize** [comment]
**In training, I set the parameters as**
use_deeplab = False
starting_from_cityscapes = False
starting_from_imagenet = False or True

**The result shows that no value is saved, I just don't want to use deeplab's model here.The error is as follows:**
Traceback (most recent call last):
  File "nuscenes_train.py", line 1425, in <module>
    main()
  File "nuscenes_train.py", line 1418, in main
    run_training(continue_run)
  File "nuscenes_train.py", line 540, in run_training
    imagenet_image_saver = tf.train.Saver(image_variables_to_restore)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 865, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by ybarancan** [comment]
Hi,
The code currently only supports Deeplab Xception. I will update it with Resnet support . But you can also change it and use whichever backbone you want.  To do that, change image_encoder function in mem_net.py (line 966). 
The lines 490 - 540 in train.py deals with loading the weights from the pre-trained backbones. So when you use your own backbonei you will need to change the names so that the checkpoint can be loaded.

**Comment by ShangWeize** [comment]
**Hi, I tried test.py again, using the provided model.The model is as follows：**
bev-stitch-nusc/
routine-39999.data-00000-of-00001
routine-39999.index
routine-39999.meta

**The parameters are set to:**
use_deeplab = True
starting_from_cityscapes = True
starting_from_imagenet = False

**But the following error occurs：**
INFO:tensorflow:Restoring parameters from /home/bev-stitch-nusc
2022-03-02 20:25:59,759 Restoring parameters from /home/bev-stitch-nusc
2022-03-02 20:26:00.899797: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/bev-stitch-nusc: Failed precondition: /home/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2022-03-02 20:26:00.901348: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/bev-stitch-nusc: Failed precondition: /home/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2022-03-02 20:26:00.901394: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file /home/bev-stitch-nusc: Failed precondition: /home/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: Unable to open table file /home/bev-stitch-nusc: Failed precondition: /home/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
         [[{{node save/RestoreV2}}]]
  (1) Data loss: Unable to open table file /home/bev-stitch-nusc: Failed precondition: /home/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_133]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nuscenes_test.py", line 837, in <module>
    main()
  File "nuscenes_test.py", line 831, in main
    run_training(continue_run)
  File "nuscenes_test.py", line 403, in run_training
    saver.restore(sess,load_path)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: Unable to open table file /home/bev-stitch-nusc: Failed precondition: /home/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at /home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Data loss: Unable to open table file /home/Documents/swz/bev-stitch-nusc: Failed precondition: /home/leewanlong/Documents/swz/bev-stitch-nusc; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at /home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[save/RestoreV2/_133]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "nuscenes_test.py", line 837, in <module>
    main()
  File "nuscenes_test.py", line 831, in main
    run_training(continue_run)
  File "nuscenes_test.py", line 392, in run_training
    saver = tf.train.Saver(max_to_keep=2)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build
    build_restore=build_restore)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/anaconda3/envs/open-mmlab2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by synsin0** [comment]
I tested and found both 'all_images_list' and 'all_labels_list' are empty []. The reason is that I don't know how to set nuscenes_processed_root like your '/srv/beegfs02/scratch/tracezuerich/data/cany'. I run make_nuscenes_labels.py but I think '../monomaps_labels_vanilla' corresponds to 'nuscenes_bev_root'. So is there any more pre-processing codes?

**Comment by synsin0** [comment]
Sorry that I neglect data_creator.py. I will try that and continue training.

**Comment by synsin0** [comment]
During training, another problem occurs. Environment: tensorflow==1.15.0 numpy==1.19.5

error info:
ERROR:root:NUMBER OF ALL PARAMETERS: 21628933
ERROR:root:NUMBER OF BACKBONE PARAMETERS: 10206576
WARNING:tensorflow:From /home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1375: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1375: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2380, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'tensorflow_ground_transform_1/ImageProjectiveTransformV2' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 345, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 2384, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'tensorflow_ground_transform_1/ImageProjectiveTransformV2' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "argoverse_train.py", line 1316, in <module>
    main()
  File "argoverse_train.py", line 1311, in main
    run_training(continue_run)
  File "argoverse_train.py", line 551, in run_training
    gvs = optimizer.compute_gradients(loss,var_list=optimizer_variables)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 679, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 350, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/gradients_util.py", line 679, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/contrib/image/python/ops/image_ops.py", line 420, in _image_projective_transform_grad
    transforms = flat_transforms_to_matrices(transforms=transforms)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/contrib/image/python/ops/image_ops.py", line 362, in flat_transforms_to_matrices
    [transforms, array_ops.ones([num_transforms, 1])], axis=1),
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2560, in ones
    output = _constant_if_small(one, shape, dtype, name)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3052, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (gradients/tensorflow_ground_transform_1/ImageProjectiveTransformV2_grad/flat_transforms_to_matrices/strided_slice:0) to a numpy array.

Another error may be from the same source:
Traceback (most recent call last):
  File "argoverse_train.py", line 1316, in <module>
    main()
  File "argoverse_train.py", line 1311, in main
    run_training(continue_run)
  File "argoverse_train.py", line 320, in run_training
    side_obj_loss, _ = mem_net.classwise_object_loss(side_obj_softmaxed,image_objects_label_placeholder,tf.slice(image_labels_placeholder,[reference_frame_index,0,0,exp_config.num_classes+1],[1,-1,-1,-1]),exp_config,alpha_pos,weight=True,weight_vector=None, focal=True)
  File "/home/yining/BEV_feat_stitch/mem_net.py", line 53, in classwise_object_loss
    alpha_neg = tf.constant(np.ones_like(alpha_pos), tf.float32)
  File "<__array_function__ internals>", line 6, in ones_like
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/numpy/core/numeric.py", line 280, in ones_like
    res = empty_like(a, dtype=dtype, order=order, subok=subok, shape=shape)
  File "<__array_function__ internals>", line 6, in empty_like
  File "/home/yining/anaconda3/envs/tf1_env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (Const_8:0) to a numpy array.


I changed  'alpha_neg = tf.constant(np.ones_like(alpha_pos), tf.float32)' to 'alpha_neg = tf.ones_like(alpha_pos,tf.float32)'. It seems works. But I failed to find the solution of the first error regarding  optimizer.compute_gradients.

**Comment by ybarancan** [comment]
I don't know about xlacompile error. It is something to do with your environment. Maybe tensorflow version (I used 1.14)  or cuda version or a missing package in your environment.

**Comment by synsin0** [comment]
Thanks. tensorflow==1.14.0 works for me. Now the training process starts normally. You are so helpful!

**Comment by ShangWeize** [comment]
**Does the preload parameter need to be obtained by training the cityscapes dataset through deeplab?**
 /scratch_net/catweazle/cany/cityscapes_deeplab/model.ckpt
**I can't find this file**

**Comment by ybarancan** [comment]
https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md

You can download 
[xception65_cityscapes_trainfine](http://download.tensorflow.org/models/deeplabv3_cityscapes_train_2018_02_06.tar.gz)

Note that the checkpoints are sometimes updated to accomodate changes in TF version. So it might need some tweaking.

**Comment by ShangWeize** [comment]
**Thanks for your guidance, I can run it successfully now!I‘m so happy!!!**

**Comment by YuZai-SYH** [comment]
> After changing line 50 in deeplab/common.py the error is solved. After the training process starts, another error during training process is like: 2022-03-01 11:50:28,726 EPOCH : 0 2022-03-01 11:50:28,829 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:28,933 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,037 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,140 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,244 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,348 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,451 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,554 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,658 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,761 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,865 Exception empty range for randrange() (0,-2, -2) ......
> 
> It appears very quickly and stays constant, so I guess it may be a image cropping problem. Look forward to your reply.

hi，can you share the way to solve this. problem

**Comment by YuZai-SYH** [comment]
> After changing line 50 in deeplab/common.py the error is solved. After the training process starts, another error during training process is like: 2022-03-01 11:50:28,726 EPOCH : 0 2022-03-01 11:50:28,829 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:28,933 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,037 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,140 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,244 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,348 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,451 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,554 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,658 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,761 Exception empty range for randrange() (0,-2, -2) 2022-03-01 11:50:29,865 Exception empty range for randrange() (0,-2, -2) ......
> 
> It appears very quickly and stays constant, so I guess it may be a image cropping problem. Look forward to your reply.

I have the same question as you.how did you solve it？
